### ISSUE TITLE
Are there any example to show how to use the framework?

### ISSUE THREAD

**Issue by firewood1996** [EdgeSimPy/EdgeSimPy#1]
Actually, i don't konw how to use this framework to create a simple appliacation. Could you please provide a simple example to show how to use it?

**Comment by paulosevero** [comment]
Hi @firewood1996! Thanks for the message.

Our tutorials repository has a list of hands-on tutorials ([link here](https://github.com/EdgeSimPy/edgesimpy-tutorials)). There you will find guides on installing (which basically requires running `pip install git+https://github.com/EdgeSimPy/EdgeSimPy.git@v1.0.0`), creating heuristics (e.g., application placement and application migration), and extending the simulator for other specific purposes.

The README.md of the tutorials repository has links for executing the tutorials with online Jupyter platforms, so you don't have to install anything locally to get EdgeSimPy up and running.

Please notice that EdgeSimPy is still in its early stages. We're working hard to add more features and tutorials on using the simulator. Stay tuned because there's some exciting stuff coming in the next couple of months.

If you have any further questions, please let us know.
